# Site
repository: iknoom/iknoom.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최문기(Moonki Choi)
title: Backend Developer
email: iknoom@kakao.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  iknoom
linkedin_username: moonki-choi-7139051b1

# Additional icon links
additional_links:
- title: iknoom.tistory.com
  icon: fas fa-globe
  url: https://iknoom.tistory.com

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  // 간단한 자기소개

  // 흥미

  I am interested in <mark>Java/Spring</mark>, <mark>Algorithm</mark>

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: 서울시립대학교
        caption: 2016.3 - 2022.2(졸업 예정)
        sub_title: 컴퓨터과학부
        description: |
          // 기본기, 학점보다는 지속성을 위한 기록

          // 학점

          // 장학금

          - 운영체제
          - 네트워크
          - 프로그래밍 언어론
          - 인공지능
          - 웹정보, 소응

  - title: Study
    layout: list
    content:
      - layout: top-middle
        title: Backend-Study
        link: https://github.com/ddbreaker/Backend-Study/tree/main/iknoom
        link_text: github.com/ddbreaker/Backend-Study/tree/main/iknoom
        additional_links:
          - title:  ddbreaker/Backend-Study/tree/main/iknoom
            icon: fab fa-github
            url: github.com/ddbreaker/Backend-Study/tree/main/iknoom
        quote: >
          이 프로젝트는..
        description: |
          // 설명 및 공부한 내용

  - title: Projects
    layout: list
    content:
      # Project #1
      - layout: top-middle
        title: ColorAid
        sub_title: 웹툰 밑색 자동 채색 어플리케이션
        link: https://github.com/UOS-SamSam/UOSwing-backend
        link_text: github.com/UOS-SamSam/UOSwing-backend
        additional_links:
          - title:  UOS-SamSam/UOSwing-backend
            icon: fab fa-github
            url: github.com/UOS-SamSam/UOSwing-backend
          - title:  play.google.com/store/apps/details?id=com.uoswing
            icon: fas fa-globe
            url: https://play.google.com/store/apps/details?id=com.uoswing
        quote: >
          이 프로젝트는..
        description: |
          // 설명 및 맡은 역할
      # Project #2
      - layout: top-middle
        title: Project Wing
        sub_title: 서울시립대학교 양심생리대함 App
        link: https://github.com/UOS-SamSam/UOSwing-backend
        link_text: github.com/UOS-SamSam/UOSwing-backend
        additional_links:
          - title:  UOS-SamSam/UOSwing-backend
            icon: fab fa-github
            url: github.com/UOS-SamSam/UOSwing-backend
          - title:  play.google.com/store/apps/details?id=com.uoswing
            icon: fas fa-globe
            url: https://play.google.com/store/apps/details?id=com.uoswing
        quote: >
          이 프로젝트는..
        description: |
          // 설명 및 맡은 역할
      # Project #3
      - layout: top-middle
        title: BOJ-BREAKER
        sub_title: 우리 학교가 풀지 않은 Baekjoon 문제
        link: https://github.com/ddbreaker/BOJ-BREAKER
        link_text: github.com/ddbreaker/BOJ-BREAKER
        additional_links:
          - title:  github.com/ddbreaker/BOJ-BREAKER
            icon: fab fa-github
            url: github.com/ddbreaker/BOJ-BREAKER
        quote: >
          이 프로젝트는..
        description: |
          // 설명 및 맡은 역할
  
  - title: Undergraduate Projects & Toy Projects
    layout: text
    content: |
      ## `2020.09-2020.12` CNN을 이용한 자율주행자동차 
      - [Github Link](https://github.com/iknoom/AI_RC_Car)
      - `Python`, `Keras`
      
      ## `2020.07` 파파고 api를 활용한 반투명 클립보드 번역 앱 
      - [Github Link](https://github.com/iknoom/clipboard_translator)
      - `Python`, `PyQt`

      ## `2020.03` 알고리즘 대회 일정 알림 Slack Bot 
      - [Github Link](https://github.com/ManManChiAnunTeam/project-ihb/tree/master/contests_notice)
      - `Python`, `AWS Lambda`, `BeautifulSoup`

  - title: Problem Solving
    layout: text
    content: | 
      ## Site
      ![atcoder](https://cp-logo.vercel.app/atcoder/IKnoom)
      ![codeforces](https://cp-logo.vercel.app/codeforces/IKnoom)
      [![solved.ac](http://mazassumnida.wtf/api/mini/generate_badge?boj=iknoom1107)](https://solved.ac/iknoom1107)
      - [Atcoder](https://atcoder.jp/users/IKnoom)
      - [Codeforces](http://codeforces.com/profile/IKnoom)
      - [Baekjoon Online Judge](https://www.acmicpc.net/user/iknoom1107)

      ## History
      - 2021 SCPC(삼성 대학생 프로그래밍 경진대회) **본선 진출**
      - 2020 ACM-ICPC Asia Seoul Regional Contest **본선 28등**(ICPC rule 14등)
      - 2020 UOSPC(서울시립대학교 알고리즘 경진대회) **운영, 출제 및 검수**
      - 2020 서울시립대학교 알고리즘 소모임 AL林 **회장**
      - 2019 UOSPC(서울시립대학교 알고리즘 경진대회) **출제 및 검수**
      
  - title: Language
    layout: text
    content: | 
      ## Japanese
      - JLPT N3 취득 (157/180점, 2017.01.22)
      - JLPT N2 취득 (145/180점, 2018.08.19)
      - JLPT N1 응시예정 (2021.12.05)
      
  - title: Memo
    layout: text
    content: | 
      ## TODO
      - KR font 수정
      - SlideShare 넣기

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
